//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGroup
    {
        public long Id { get; set; }
        public long UserAccount { get; set; }
        public int UserGroup { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int Status { get; set; }
    
        public virtual UserAccount UserAccount1 { get; set; }
        public virtual UserGroup UserGroup1 { get; set; }
    }
}
