//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketOrderDetail
    {
        public long Id { get; set; }
        public long TicketOrder { get; set; }
        public int OrderType { get; set; }
        public Nullable<int> Person { get; set; }
        public string TableNo { get; set; }
        public string Remark { get; set; }
        public System.DateTime Createdate { get; set; }
        public System.DateTime Lastdate { get; set; }
        public int Status { get; set; }
    }
}
